### ISSUE TITLE
Test FFI bindings with ctest

### ISSUE THREAD

**Issue by kaedroho** [rust-rocksdb/rust-rocksdb#124]
Might be useful to implement this for automatically testing the FFI bindings: https://github.com/alexcrichton/ctest

**Comment by spacejam** [comment]
This looks cool! Adding this would be great

**Comment by spacejam** [comment]
What are your thoughts on https://github.com/spacejam/rust-rocksdb/issues/128 ? While it doesn't completely get rid of the need to test, since the generator could always be broken, it would be nice if we could automatically generate the FFI bindings to keep up with rocksdb's c API in a less error-prone way.

**Comment by iSynaptic** [comment]
Closing this since it seems using bindgen was the solution.
