### ISSUE TITLE
Move the project to an organization

### ISSUE THREAD

**Issue by aleksuss** [rust-rocksdb/rust-rocksdb#204]
@spacejam, @ekmartin 
 
Thank you for putting together and open-sourcing Rust RocksDB project. We at Exonum have been using it for more than a year and are interested in its further development.

Our team is grateful to you for reviewing and integrating our patches so far, however, it seems to us the project has ceased to be your top priority recently. For this reason, I suggest moving it under a new organization “rust-rocksdb” and giving more people permission to integrate changes and publish new versions of it on crates.io. In this way the project can evolve, enlarge its community, acquire better maintenance and improve in quality.

We understand it takes efforts maintaining an open-source project and would like to offer help with that. As you may know, members of Exonum team — @DarkEld3r, @ozkriff  — have contributed various fixes and improvements to Rust RocksDB. Our team has expertise in running open-source projects in Rust, Exonum being the most prominent example.

Please consider further development of your project in a modified manner as suggested above and let us know your thoughts on the matter. You are free to contact our team members or me directly for discussion.

**CC** recent contributors: @kaedroho @alexreg @dgrnbrg @derekdreery

**Comment by Kais-DkM** [comment]
@spacejam @aleksuss Is there any progress on this?

**Comment by derekdreery** [comment]
I'd consider reaching out to the rust/crates.io team about forking the
project under an organization and changing the crates.io package.

**Comment by spacejam** [comment]
I'm in favor of transferring ownership of the root repo and crate to the rust-rocksdb org, which I just created. This should have been done a long time ago to avoid the fragmentation that has occurred.

This also brings up the question of whether it is possible to combine forces with some of the organizations that have forked this project and continue to invest significant resources into pushing it in the directions that they require.

@pingcap (@zhangjinpeng1987, @huachaohuang, @BusyJay, @siddontang, @hoverbear) If there is the willingness to combine efforts, now is probably the "now or never" moment to pool resources, but there are some good reasons for staying independent as well. First, as a business with code dependencies, you can't be beholden to outside control over the libraries that you rely on, but it may be advantageous to build TiKV and any other internal users on top of a "shallow fork" under pingcap control so that you can take advantage of things like windows support etc... while still having total control over the version that is depended on internally. With a proper org running rust-rocksdb, which you can be maintainers for if you are interested in collaborating, you will have way less friction to get the changes you need merged in compared to what was the case with just me running it before you stopped wanting to deal with the friction by just running your own fork, but this will be higher than the way you're running your fork independently now. So, please chip in if you think the trade-off is worthwhile at this time for pingcap to pool resources. No pressure, but I wanted to let you folks know that this is happening here and it might be an opportunity that you are interested in!

@kaedroho  @ongardie-ebay @alexreg @derekdreery you folks were previously also submitting plenty of patches before I assume you got fed up with my slow response rate :P Would you benefit from being a maintainer in this new organization?

@alexsuss Thank you for volunteering to take on maintainer responsibilities! This is going to be a great thing for the project, I think. Do you have any strong preferences for how maintainers should reach consensus, and on what consensus is required, and how contributors should be engaged?

**Comment by spacejam** [comment]
Also @paritytech / @andresilva let me know if this is something you folks have interest in participating in!

**Comment by aleksuss** [comment]
@spacejam thanks for your response. I propose next flow for contributing:  

- Any change must go as a pull request.
- Any PR must have at least two approvals from the team members (ideally, from people with expertise in various things).

For anything non-trivial, e.g., breaking changes, new features, I'd add:
- A maintainer must leave a two working days window for other team members to be able to review the change.

Any additions are welcome. Thanks.

**Comment by ongardie-ebay** [comment]
Just a quick response since @spacejam mentioned me: I haven't been contributing lately simply because I've been stuck over in Go-land. Of course, it'd be great to see this project actively maintained.

**Comment by siddontang** [comment]
@spacejam 

In TiKV, we have changed a lot from the origin repo, and I think it is not suitable to contribute our change now.

But we are very happy to offer help if possible.

**Comment by kaedroho** [comment]
> @kaedroho @ongardie-ebay @alexreg @derekdreery you folks were previously also submitting plenty of patches before I assume you got fed up with my slow response rate :P Would you benefit from being a maintainer in this new organization?

Had no problems with your response rate :). Just haven't worked on rusticsearch in a while. I'd be happy to help out with maintaining this though!

> Any PR must have at least two approvals from the team members (ideally, from people with expertise in various things).

Given that nobody is actually paid to review PRs for this project, getting just one approval will take time in most cases (see current PR list). And I think for most changes one approval is enough, but I agree that for non-trival stuff (such as major API changes and internal refactoring) should be given a chance to gather more feedback. I don't think 2 days is enough for this though, two weeks sounds more realistic to me (people go on holidays, work trips, etc).

**Comment by spacejam** [comment]
I agree with @kaedroho that 2 days is a very short turnaround time. I think there are some times when a week would also be hard to find time for a really major review, and 2 weeks is probably more realistic given people may be on vacation or simply having a busy week. Personally, I'm an excruciatingly slow reader of code, and I can easily spend an hour re-learning the parts of the codebase that a small PR touches. 

So, I propose 2 weeks as the "well, I tried to involve others, but there was no response, so I moved forward" timeout for feedback generation on a major change.

"Major change" is going to be a bit subjective. I'll trust maintainers to use their judgment to involve others early when something beyond small / routine changes happens.

Small / routine changes that can move fast, and I don't feel like I need to be involved in, but should ideally still have 2 approvals:
* updating librocksdb-sys 
* tracking API changes without changing control flow in existing code

Historically, this repo has been a battleground for people with different refactoring ideas to more or less run wild. People have started to use the language in a more uniform way since 2014, and we can probably be more cautious about this now. My philosophy before was to just let people tidy things up in a way that will make them feel more at home, to encourage continued contribution. I think now we should be a little more cautious about refactoring for refactoring's sake, and it should probably come with some justification.

I'm going to add the [contributor covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.txt) as our code of conduct. Everything I've said is up for debate except for having one.

So, soon-to-be-maintainers (anyone who has been @-mentioned on this thread, although this will be opt-in, so if you disagree with the code of conduct you can just pretend to be afk :P), **what are your opinions about**:
1. normal changes require 2 approvals
1. 2 week timeout on feedback for major changes, after which there is no need to get more than 2 approvals for merging
1. defining small changes that do not require more than 2 approvals as 
    a. a librocksdb-sys update
    b. API tracking code in the rocksdb crate that does not change control flow
1. encouraging refactoring to happen for clearly functional reasons, like improving ability to reason about correctness or to ease a feature's implementation
1. major changes require consensus among participants. If something needs to happen, and there are disagreements about what should happen, I can act as a tiebreaker if requested but I prefer not to use this ever.

**Comment by spacejam** [comment]
As we draw near to the 2 week mark for the above comment, I'd like to invite more feedback on the proposed process, although I think at this point it's fine to start acting on it. I've sent @aleksuss an invite to this org, and I've created a team with permission to publish to crates.io: `crate-publishers`

If anyone else would like to opt-into maintainership responsibilities, please either leave a message here so I can see it, or feel free to send me an email at t@jujit.su.

**Comment by spacejam** [comment]
@iSynaptic yeah! I'll create a proposal PR now that formalizes this
