### ISSUE TITLE
lifetime in ColumnFactory

### ISSUE THREAD

**Issue by stalexxx** [rust-rocksdb/rust-rocksdb#278]
First of all, thank you for your work)
Next thing: in new release you have added livetime to ColumnFactory, but we have structure like this

`
struct Writer {
  db: DB, 
  column: ColumnFactory
}
`
we keep `column` just to avoid writing `self.db.cf_handle("something").unwrap()` all the time (and save some time on readlock), but having lifetime in Writer is not what we want. So, we thought, maybe there is a reason not keeping columns?

**Comment by iSynaptic** [comment]
The lifetime was added to the `ColumnFamily` struct because it contains a pointer to a C structure. If the structure was allowed to outlive the `DB` structure, the pointer contained within the `ColumnFamily` struct would be dangling.  The same was true of `DBRawIterator` and `DBIterator` -- both now have lifetimes.

I've got some ideas that would allow `ColumnFamily` not to contain a pointer (and not need a lifetime parameter) or make the `cf_handle` call much cheaper, or both - something I've wanted to do even before you logged this issue.  But adding the lifetime was the most direct solution to the dangling pointer issue.  I've created a #279 to remind us to make the change.
