### ISSUE TITLE
Mutli-thread reading

### ISSUE THREAD

**Issue by pakipaki2000** [rust-rocksdb/rust-rocksdb#282]
Hi,

I can't find any example of using an Arc with Rocksdb to do concurrent reading.
Any working example? :(

Thank you.

**Comment by rohitjoshi** [comment]
See example [here](https://github.com/rohitjoshi/bhatho/blob/master/src/db/db_manager.rs)

**Comment by iSynaptic** [comment]
@rohitjoshi Thanks for providing an example.

@pakipaki2000 There is nothing special about how `DB` and `Arc` works together.  You can use `DB` with `Arc` the same way you would use any struct with `Arc`.  The [official Rust documentation](https://doc.rust-lang.org/std/sync/struct.Arc.html) and the [Rust book](https://doc.rust-lang.org/book/ch16-03-shared-state.html#atomic-reference-counting-with-arct) can cover using `Arc` far better than we can here. Since `DB` is `Send` and `Sync`, you do **not** need to use any locks (eg `Mutex`) to provide synchronized access - you just need to make sure the `DB` stays alive long enough for it to be valid for all threads. That is what `Arc` provides.
