### ISSUE TITLE
Handling of OpenDB with TTL

### ISSUE THREAD

**Issue by jo2wan** [rust-rocksdb/rust-rocksdb#297]
Hello,

If I am not wrong, the current crate does not support TTL feature, if so, do you plan to support OpenDB with time to live (TTL) option?

I know that there is an ongoing code refactoring which should bring more flexibility (like ReadOnly DB support and many more ...), maybe TTL feature will be also bundled by #268

**Comment by iSynaptic** [comment]
It's definitely something we'd like to support, but #268 probably isn't going to add support for it. That PR is already pretty big.  I'm working through simplifying the changes in #268 to get it landed sooner rather than later. Increasing the scope will only delay it longer.  I'll leave this issue open as a reminder to revisit and implement this.

**Comment by acrrd** [comment]
Does #425 address this?

**Comment by DarkEld3r** [comment]
@acrrd I suppose it is.

@jo2wan Feel free to reopen this issue if #425 is missing something.
