### ISSUE TITLE
Merge: How to disable partial merge

### ISSUE THREAD

**Issue by zach-schoenberger** [rust-rocksdb/rust-rocksdb#566]
There does not seem to be a way to use the merge functionality without implementing partial merge. This is doable in the C++ library.

**Comment by akrylysov** [comment]
rust-rocksdb uses the C RocksDB API. When you call [rocksdb_mergeoperator_create](https://github.com/facebook/rocksdb/blob/dc5de45af8fc1bcc90edea5cd9a5695bd85a8baf/include/rocksdb/c.h#L1625) you have to provide `partial_merge` function. There is no way to disable partial merge in rust-rocksdb because C RocksDB API doesn't provide it.
