### ISSUE TITLE
`delete_range` and `delete_range_cf` not implemented for `TransactionDB` or `OptimisticTransactionDB`

### ISSUE THREAD

**Issue by mdecimus** [rust-rocksdb/rust-rocksdb#839]
Methods `delete_range` and `delete_range_cf` are only available when using `DB` but not on `TransactionDB` or `OptimisticTransactionDB`.

**Comment by vadim-su** [comment]
Could you let me know if you found a solution?

**Comment by vadim-su** [comment]
Well, I have made the solution for `OptimisticTransactionDB`. Although I am not entirely sure that the solution correctly utilizes a RocksDB function, it appears to be functioning properly for my needs 44d0f98cfb0a87ba18d0f9167c4093131ac8956c

It can't use Transaction and TransactionDB because of restrictions of the original library, but I have been able to integrate these functions for the Optimistic version of db because Optimistic contains rocksdb_t as an inner db pointer. That's why I'm not sure about properly working :sweat_smile:
